// ===========================================
// AGENT ERROR REGISTRY — ALL CODES (800-869)
// ===========================================
// Merged from error-registry-core (800-839) and
// error-registry-chat (840-869). Single registry
// for the @ordinatio/agent package.
// ===========================================

export interface AgentErrorEntry {
  code: string;
  file: string;
  function: string;
  httpStatus: number;
  severity: 'info' | 'warning' | 'error' | 'critical';
  recoverable: boolean;
  description: string;
  diagnosis: string[];
}

export const AGENT_ERRORS: Record<string, AgentErrorEntry> = {
  // ---- Provider errors (800-809) ----
  AGENT_800: {
    code: 'AGENT_800',
    file: 'providers/provider-factory.ts',
    function: 'getProvider',
    httpStatus: 500,
    severity: 'error',
    recoverable: false,
    description: 'Unknown LLM provider requested',
    diagnosis: [
      'Check LLM_PROVIDER env var — supported values: claude, openai, gemini, deepseek, mistral, grok',
      'Verify the provider module exists in providers/ directory',
    ],
  },
  AGENT_801: {
    code: 'AGENT_801',
    file: 'providers/claude-provider.ts',
    function: 'chat',
    httpStatus: 502,
    severity: 'error',
    recoverable: true,
    description: 'Claude API call failed',
    diagnosis: [
      'Check ANTHROPIC_API_KEY env var is set',
      'Verify API key has not expired',
      'Check Anthropic API status page for outages',
    ],
  },
  AGENT_802: {
    code: 'AGENT_802',
    file: 'providers/openai-provider.ts',
    function: 'chat',
    httpStatus: 502,
    severity: 'error',
    recoverable: true,
    description: 'OpenAI API call failed',
    diagnosis: [
      'Check OPENAI_API_KEY env var is set',
      'Verify API key has not expired',
      'Check OpenAI API status page for outages',
    ],
  },
  AGENT_803: {
    code: 'AGENT_803',
    file: 'providers/gemini-provider.ts',
    function: 'chat',
    httpStatus: 502,
    severity: 'error',
    recoverable: true,
    description: 'Google Gemini API call failed',
    diagnosis: [
      'Check GEMINI_API_KEY env var is set',
      'Verify API key has not expired or been revoked',
      'Check Google AI Studio status page for outages',
      'Ensure @google/generative-ai package is installed',
    ],
  },
  AGENT_804: {
    code: 'AGENT_804',
    file: 'providers/deepseek-provider.ts',
    function: 'chat',
    httpStatus: 502,
    severity: 'error',
    recoverable: true,
    description: 'DeepSeek API call failed',
    diagnosis: [
      'Check DEEPSEEK_API_KEY env var is set',
      'Verify API key is valid at platform.deepseek.com',
      'Check DeepSeek API status for outages',
      'Verify baseURL: https://api.deepseek.com is reachable',
    ],
  },
  AGENT_805: {
    code: 'AGENT_805',
    file: 'providers/mistral-provider.ts',
    function: 'chat',
    httpStatus: 502,
    severity: 'error',
    recoverable: true,
    description: 'Mistral AI API call failed',
    diagnosis: [
      'Check MISTRAL_API_KEY env var is set',
      'Verify API key is valid at console.mistral.ai',
      'Check Mistral API status for outages',
      'Verify baseURL: https://api.mistral.ai/v1 is reachable',
    ],
  },
  AGENT_806: {
    code: 'AGENT_806',
    file: 'providers/grok-provider.ts',
    function: 'chat',
    httpStatus: 502,
    severity: 'error',
    recoverable: true,
    description: 'xAI Grok API call failed',
    diagnosis: [
      'Check XAI_API_KEY env var is set',
      'Verify API key is valid at console.x.ai',
      'Check xAI API status for outages',
      'Verify baseURL: https://api.x.ai/v1 is reachable',
    ],
  },

  // ---- Role/Tool errors (810-819) ----
  AGENT_810: {
    code: 'AGENT_810',
    file: 'registry/role-registry.ts',
    function: 'getRole',
    httpStatus: 404,
    severity: 'error',
    recoverable: false,
    description: 'Unknown agent role requested',
    diagnosis: [
      'Check role ID — verify the role was registered via registerRole()',
      'Verify the role is registered before querying',
    ],
  },
  AGENT_811: {
    code: 'AGENT_811',
    file: 'registry/tool-registry.ts',
    function: 'getToolsForRole',
    httpStatus: 404,
    severity: 'warning',
    recoverable: true,
    description: 'No tools found for the requested role',
    diagnosis: [
      'Check that tools are registered for this role via registerTools()',
      'Verify the role has modules with associated tools',
    ],
  },
  AGENT_812: {
    code: 'AGENT_812',
    file: 'registry/tool-registry.ts',
    function: 'getTool',
    httpStatus: 404,
    severity: 'warning',
    recoverable: true,
    description: 'Tool not found by name',
    diagnosis: [
      'Check tool name — use snake_case',
      'Verify the tool was registered via registerTool() or registerTools()',
    ],
  },

  // ---- Email draft errors (820-829) ----
  AGENT_820: {
    code: 'AGENT_820',
    file: 'api/email/drafts/route.ts',
    function: 'POST',
    httpStatus: 400,
    severity: 'warning',
    recoverable: true,
    description: 'Invalid email draft creation request',
    diagnosis: [
      'Check required fields: toEmail, subject, bodyHtml',
      'Verify email address format is valid',
    ],
  },
  AGENT_821: {
    code: 'AGENT_821',
    file: 'api/email/drafts/[id]/route.ts',
    function: 'GET',
    httpStatus: 404,
    severity: 'warning',
    recoverable: true,
    description: 'Email draft not found',
    diagnosis: [
      'Verify the draft ID is correct',
      'Check if the draft was already sent or deleted',
    ],
  },
  AGENT_822: {
    code: 'AGENT_822',
    file: 'api/email/drafts/[id]/send/route.ts',
    function: 'POST',
    httpStatus: 409,
    severity: 'warning',
    recoverable: false,
    description: 'Cannot send draft — not in DRAFT status',
    diagnosis: [
      'Draft may have already been sent, cancelled, or is processing',
      'Check draft status via GET /api/email/drafts/{id}',
    ],
  },
  AGENT_823: {
    code: 'AGENT_823',
    file: 'api/email/drafts/[id]/send/route.ts',
    function: 'POST',
    httpStatus: 500,
    severity: 'error',
    recoverable: true,
    description: 'Failed to send email draft',
    diagnosis: [
      'Check email provider OAuth connection is active',
      'Verify email account is connected in Settings',
      'Check recipient email address is valid',
    ],
  },

  // ---- Approval gate errors (830-839) ----
  AGENT_830: {
    code: 'AGENT_830',
    file: 'orchestrator/orchestrator.ts',
    function: 'approvalGate',
    httpStatus: 403,
    severity: 'warning',
    recoverable: true,
    description: 'Action requires human approval',
    diagnosis: [
      'This action has an approval gate — the agent must request human approval',
      'Present the approval prompt to the user and wait for confirmation',
    ],
  },

  // ---- Memory errors (840-849) ----
  AGENT_840: {
    code: 'AGENT_840',
    file: 'memory/memory-service.ts',
    function: 'createMemory',
    httpStatus: 400,
    severity: 'warning',
    recoverable: true,
    description: 'Memory creation failed — invalid or missing parameters',
    diagnosis: [
      'Check that summary (string) and layer (TEMPORARY|DEEP) are provided',
      'If tagging, verify tag names are non-empty strings (max 50 chars each)',
      'If entity-scoped, verify clientId/orderId exist in the database',
      'Check Zod validation errors in the context.validationErrors array',
    ],
  },
  AGENT_841: {
    code: 'AGENT_841',
    file: 'memory/memory-service.ts',
    function: 'createMemory',
    httpStatus: 500,
    severity: 'error',
    recoverable: true,
    description: 'Database write failed while persisting memory',
    diagnosis: [
      'Check DATABASE_URL in .env.local',
      'Verify AgentMemory table exists (run pnpm db:push)',
      'Check Prisma logs for constraint violations',
      'If entity-scoped, verify foreign key references exist',
    ],
  },
  AGENT_842: {
    code: 'AGENT_842',
    file: 'memory/memory-service.ts',
    function: 'recallMemories',
    httpStatus: 400,
    severity: 'warning',
    recoverable: true,
    description: 'Invalid recall query — no search criteria provided',
    diagnosis: [
      'At least one filter is required: role, layer, clientId, orderId, query, or tags',
      'Tags should be comma-separated in the query string: ?tags=vendor,delay',
      'Layer must be TEMPORARY or DEEP',
    ],
  },
  AGENT_843: {
    code: 'AGENT_843',
    file: 'memory/memory-service.ts',
    function: 'recallMemories',
    httpStatus: 500,
    severity: 'error',
    recoverable: true,
    description: 'Database query failed during memory retrieval',
    diagnosis: [
      'Check DATABASE_URL in .env.local',
      'Inspect query params in context for malformed values',
      'Check for index issues on role, layer, clientId, orderId columns',
    ],
  },
  AGENT_844: {
    code: 'AGENT_844',
    file: 'memory/memory-service.ts',
    function: 'deleteMemory',
    httpStatus: 404,
    severity: 'warning',
    recoverable: true,
    description: 'Memory not found — may have already been deleted or expired',
    diagnosis: [
      'Verify memoryId exists in the AgentMemory table',
      'If TEMPORARY, check if the memory auto-expired (expiresAt passed)',
      'Check that the memory was not already deleted by another request',
    ],
  },
  AGENT_845: {
    code: 'AGENT_845',
    file: 'memory/memory-formatter.ts',
    function: 'getMemoryContext',
    httpStatus: 500,
    severity: 'error',
    recoverable: true,
    description: 'Failed to assemble memory context for system prompt',
    diagnosis: [
      'Check that role query parameter is provided',
      'If clientId/orderId provided, verify they exist in the database',
      'Check ActivityLog access for timeline assembly',
      'Verify database connectivity',
    ],
  },
  AGENT_846: {
    code: 'AGENT_846',
    file: 'memory/memory-service.ts',
    function: 'expireStaleMemories',
    httpStatus: 500,
    severity: 'error',
    recoverable: true,
    description: 'Cleanup job failed — stale TEMPORARY memories not purged',
    diagnosis: [
      'Check database connectivity',
      'Verify AgentMemory table exists (pnpm db:push)',
      'Check cron scheduler if running as a scheduled job',
    ],
  },
  AGENT_847: {
    code: 'AGENT_847',
    file: 'orchestrator/orchestrator.ts',
    function: 'logInteraction',
    httpStatus: 500,
    severity: 'error',
    recoverable: true,
    description: 'Failed to log agent interaction',
    diagnosis: [
      'Check database connectivity',
      'Verify AgentInteraction table exists (pnpm db:push)',
      'Check request body has a valid query string',
    ],
  },
  AGENT_848: {
    code: 'AGENT_848',
    file: 'orchestrator/orchestrator.ts',
    function: 'getInteractions',
    httpStatus: 500,
    severity: 'error',
    recoverable: true,
    description: 'Failed to fetch agent interactions',
    diagnosis: [
      'Check database connectivity',
      'Verify user session is valid',
    ],
  },
  AGENT_849: {
    code: 'AGENT_849',
    file: 'orchestrator/orchestrator.ts',
    function: 'getSuggestions',
    httpStatus: 500,
    severity: 'error',
    recoverable: true,
    description: 'Failed to fetch agent suggestions',
    diagnosis: [
      'Check database connectivity',
      'Verify AgentSuggestion table exists (pnpm db:push)',
    ],
  },

  // ---- Chat/Orchestrator errors (850-859) ----
  AGENT_850: {
    code: 'AGENT_850',
    file: 'orchestrator/orchestrator.ts',
    function: 'orchestrateChat',
    httpStatus: 400,
    severity: 'warning',
    recoverable: true,
    description: 'Invalid chat request — missing role or messages',
    diagnosis: [
      'Check that role (string) and messages (array) are provided',
      'Verify role is a registered agent ID',
      'Messages array must have at least one user message',
      'Check Zod validation errors in context for specific field failures',
    ],
  },
  AGENT_851: {
    code: 'AGENT_851',
    file: 'orchestrator/orchestrator.ts',
    function: 'orchestrateChat',
    httpStatus: 404,
    severity: 'error',
    recoverable: false,
    description: 'Unknown agent role — not registered in role-registry',
    diagnosis: [
      'Check role ID — verify it was registered via registerRole()',
      'If adding a new role, register it before using chat',
    ],
  },
  AGENT_852: {
    code: 'AGENT_852',
    file: 'orchestrator/orchestrator.ts',
    function: 'orchestrateChat',
    httpStatus: 502,
    severity: 'error',
    recoverable: true,
    description: 'LLM provider call failed during chat orchestration',
    diagnosis: [
      'Check API key for the active provider',
      'Verify LLM_PROVIDER env var is set to a valid provider (claude, openai, gemini, deepseek, mistral, grok)',
      'Check provider API status page for outages',
      'Inspect the error message in context for specific failure reason',
    ],
  },
  AGENT_853: {
    code: 'AGENT_853',
    file: 'orchestrator/tool-executor.ts',
    function: 'executeTool',
    httpStatus: 500,
    severity: 'error',
    recoverable: true,
    description: 'Tool execution failed — internal API call returned error',
    diagnosis: [
      'Check the tool name and arguments in context',
      'Verify the target API route is working (test manually)',
      'Check session cookie is valid and not expired',
      'Inspect the API response status and body in context',
    ],
  },
  AGENT_854: {
    code: 'AGENT_854',
    file: 'orchestrator/orchestrator.ts',
    function: 'orchestrateChat',
    httpStatus: 408,
    severity: 'warning',
    recoverable: true,
    description: 'Max iterations reached — agent loop exceeded limit',
    diagnosis: [
      'Agent may be stuck in a tool call loop',
      'Check if the LLM is repeatedly calling the same tool',
      'Consider simplifying the user request or breaking it into steps',
      'The partial response (if any) is included in the response',
    ],
  },
  AGENT_855: {
    code: 'AGENT_855',
    file: 'orchestrator/orchestrator.ts',
    function: 'orchestrateChat',
    httpStatus: 408,
    severity: 'warning',
    recoverable: true,
    description: 'Timeout — agent took longer than configured timeout',
    diagnosis: [
      'Complex requests with many tool calls may exceed the timeout',
      'Check if a specific tool call is slow (database query, external API)',
      'Consider breaking the request into smaller steps',
      'The timeout is configurable via OrchestratorConfig',
    ],
  },
  AGENT_856: {
    code: 'AGENT_856',
    file: 'orchestrator/prompt-builder.ts',
    function: 'buildSystemPrompt',
    httpStatus: 500,
    severity: 'error',
    recoverable: true,
    description: 'Failed to build system prompt — memory or context assembly error',
    diagnosis: [
      'Check that the role exists in role-registry',
      'Verify memory service is accessible (database connection)',
      'If pageContext includes entityId, verify the entity exists',
      'Check getMemoryContext for errors in memory-formatter',
    ],
  },
  AGENT_857: {
    code: 'AGENT_857',
    file: 'orchestrator/tool-executor.ts',
    function: 'executeTool',
    httpStatus: 403,
    severity: 'warning',
    recoverable: false,
    description: 'Tool not authorized for this role — role does not have access',
    diagnosis: [
      'Check that the tool name is in the role toolNames array',
      'Verify the tool is registered in the tool-registry',
      'The LLM may have hallucinated a tool name — check for typos',
    ],
  },
  AGENT_858: {
    code: 'AGENT_858',
    file: 'orchestrator/orchestrator.ts',
    function: 'orchestrateChat',
    httpStatus: 503,
    severity: 'info',
    recoverable: false,
    description: 'Agent chat feature is disabled via feature flag',
    diagnosis: [
      'Enable AGENT_CHAT feature flag to use agent chat',
      'Feature flags are managed by the host application',
    ],
  },
  AGENT_859: {
    code: 'AGENT_859',
    file: 'orchestrator/orchestrator.ts',
    function: 'orchestrateChat',
    httpStatus: 400,
    severity: 'warning',
    recoverable: true,
    description: 'Message too long — exceeds input token limit',
    diagnosis: [
      'The combined message history exceeds the configured maxInputTokens',
      'Try starting a new conversation to reduce context size',
      'The limit is configurable via OrchestratorConfig',
    ],
  },

  // ---- Suggestion/Analysis errors (860-869) ----
  AGENT_860: {
    code: 'AGENT_860',
    file: 'orchestrator/orchestrator.ts',
    function: 'analyzeSuggestions',
    httpStatus: 500,
    severity: 'error',
    recoverable: true,
    description: 'Failed to analyze interactions and generate agent suggestions',
    diagnosis: [
      'Check database connectivity',
      'Verify AgentInteraction table has data',
      'Check topic extraction logic',
    ],
  },
  AGENT_861: {
    code: 'AGENT_861',
    file: 'orchestrator/orchestrator.ts',
    function: 'dismissSuggestion',
    httpStatus: 500,
    severity: 'error',
    recoverable: true,
    description: 'Failed to dismiss agent suggestion',
    diagnosis: [
      'Check that suggestion ID exists',
      'Verify user session is valid',
      'Check database connectivity',
    ],
  },
  AGENT_862: {
    code: 'AGENT_862',
    file: 'orchestrator/orchestrator.ts',
    function: 'detectPatterns',
    httpStatus: 500,
    severity: 'error',
    recoverable: true,
    description: 'Pattern detection failed — could not scan activity log for automation patterns',
    diagnosis: [
      'Check database connectivity',
      'Verify ActivityLog table has recent entries',
      'Check pattern detection service for query issues',
    ],
  },
};
