// ===========================================
// @ordinatio/security — Event Configuration
// ===========================================
// Per-event risk levels, retention, tags, and alert behavior.
// ===========================================

import { SECURITY_EVENT_TYPES, type SecurityEventType, type SecurityEventConfig } from './types';

export const SECURITY_EVENT_CONFIG: Record<SecurityEventType, SecurityEventConfig> = {
  // Authentication Events
  [SECURITY_EVENT_TYPES.AUTH_LOGIN_SUCCESS]: {
    label: 'Login Success',
    description: 'User successfully authenticated',
    defaultRiskLevel: 'LOW',
    alwaysAlert: false,
    retentionDays: 90,
    tags: ['auth', 'login'],
  },
  [SECURITY_EVENT_TYPES.AUTH_LOGIN_FAILED]: {
    label: 'Login Failed',
    description: 'Authentication attempt failed',
    defaultRiskLevel: 'MEDIUM',
    alwaysAlert: false,
    retentionDays: 90,
    tags: ['auth', 'login', 'failure'],
  },
  [SECURITY_EVENT_TYPES.AUTH_LOGOUT]: {
    label: 'Logout',
    description: 'User logged out',
    defaultRiskLevel: 'LOW',
    alwaysAlert: false,
    retentionDays: 30,
    tags: ['auth', 'logout'],
  },
  [SECURITY_EVENT_TYPES.AUTH_PASSWORD_CHANGED]: {
    label: 'Password Changed',
    description: 'User changed their password',
    defaultRiskLevel: 'MEDIUM',
    alwaysAlert: false,
    retentionDays: 365,
    tags: ['auth', 'password', 'credential-change'],
  },
  [SECURITY_EVENT_TYPES.AUTH_SESSION_EXPIRED]: {
    label: 'Session Expired',
    description: 'User session expired',
    defaultRiskLevel: 'LOW',
    alwaysAlert: false,
    retentionDays: 30,
    tags: ['auth', 'session'],
  },
  [SECURITY_EVENT_TYPES.AUTH_ACCOUNT_LOCKED]: {
    label: 'Account Locked',
    description: 'Account locked due to security policy',
    defaultRiskLevel: 'HIGH',
    alwaysAlert: true,
    retentionDays: 365,
    tags: ['auth', 'lockout', 'security'],
  },
  [SECURITY_EVENT_TYPES.AUTH_SUSPICIOUS_ACTIVITY]: {
    label: 'Suspicious Activity',
    description: 'Potentially malicious authentication behavior detected',
    defaultRiskLevel: 'HIGH',
    alwaysAlert: true,
    retentionDays: 365,
    tags: ['auth', 'suspicious', 'security'],
  },
  [SECURITY_EVENT_TYPES.AUTH_MFA_ENABLED]: {
    label: 'MFA Enabled',
    description: 'Multi-factor authentication enabled for account',
    defaultRiskLevel: 'LOW',
    alwaysAlert: false,
    retentionDays: 365,
    tags: ['auth', 'mfa', 'security-improvement'],
  },
  [SECURITY_EVENT_TYPES.AUTH_MFA_DISABLED]: {
    label: 'MFA Disabled',
    description: 'Multi-factor authentication disabled for account',
    defaultRiskLevel: 'HIGH',
    alwaysAlert: true,
    retentionDays: 365,
    tags: ['auth', 'mfa', 'security-downgrade'],
  },
  [SECURITY_EVENT_TYPES.AUTH_PASSWORD_RESET_REQUESTED]: {
    label: 'Password Reset Requested',
    description: 'Password reset was requested',
    defaultRiskLevel: 'MEDIUM',
    alwaysAlert: false,
    retentionDays: 90,
    tags: ['auth', 'password', 'reset'],
  },
  [SECURITY_EVENT_TYPES.AUTH_PASSWORD_RESET_COMPLETED]: {
    label: 'Password Reset Completed',
    description: 'Password was reset via reset flow',
    defaultRiskLevel: 'MEDIUM',
    alwaysAlert: false,
    retentionDays: 365,
    tags: ['auth', 'password', 'reset', 'credential-change'],
  },

  // Access Control Events
  [SECURITY_EVENT_TYPES.PERMISSION_DENIED]: {
    label: 'Permission Denied',
    description: 'User attempted to access a resource without permission',
    defaultRiskLevel: 'MEDIUM',
    alwaysAlert: false,
    retentionDays: 90,
    tags: ['access', 'denied', 'authorization'],
  },
  [SECURITY_EVENT_TYPES.PERMISSION_GRANTED]: {
    label: 'Permission Granted',
    description: 'User was granted new permission',
    defaultRiskLevel: 'LOW',
    alwaysAlert: false,
    retentionDays: 365,
    tags: ['access', 'granted', 'authorization'],
  },
  [SECURITY_EVENT_TYPES.PERMISSION_REVOKED]: {
    label: 'Permission Revoked',
    description: 'Permission was revoked from user',
    defaultRiskLevel: 'LOW',
    alwaysAlert: false,
    retentionDays: 365,
    tags: ['access', 'revoked', 'authorization'],
  },
  [SECURITY_EVENT_TYPES.ROLE_CHANGED]: {
    label: 'Role Changed',
    description: 'User role was changed',
    defaultRiskLevel: 'MEDIUM',
    alwaysAlert: false,
    retentionDays: 365,
    tags: ['access', 'role', 'authorization'],
  },
  [SECURITY_EVENT_TYPES.UNAUTHORIZED_RESOURCE_ACCESS]: {
    label: 'Unauthorized Resource Access',
    description: 'Attempt to access resource without authorization',
    defaultRiskLevel: 'HIGH',
    alwaysAlert: true,
    retentionDays: 365,
    tags: ['access', 'unauthorized', 'security'],
  },

  // API Security Events
  [SECURITY_EVENT_TYPES.RATE_LIMIT_EXCEEDED]: {
    label: 'Rate Limit Exceeded',
    description: 'API rate limit was exceeded',
    defaultRiskLevel: 'MEDIUM',
    alwaysAlert: false,
    retentionDays: 30,
    tags: ['api', 'rate-limit'],
  },
  [SECURITY_EVENT_TYPES.API_KEY_USED]: {
    label: 'API Key Used',
    description: 'API key was used for authentication',
    defaultRiskLevel: 'LOW',
    alwaysAlert: false,
    retentionDays: 30,
    tags: ['api', 'key'],
  },
  [SECURITY_EVENT_TYPES.API_KEY_CREATED]: {
    label: 'API Key Created',
    description: 'New API key was created',
    defaultRiskLevel: 'MEDIUM',
    alwaysAlert: false,
    retentionDays: 365,
    tags: ['api', 'key', 'created'],
  },
  [SECURITY_EVENT_TYPES.API_KEY_REVOKED]: {
    label: 'API Key Revoked',
    description: 'API key was revoked',
    defaultRiskLevel: 'MEDIUM',
    alwaysAlert: false,
    retentionDays: 365,
    tags: ['api', 'key', 'revoked'],
  },
  [SECURITY_EVENT_TYPES.SECURITY_HEADER_MISSING]: {
    label: 'Security Header Missing',
    description: 'Required security header was missing from request',
    defaultRiskLevel: 'MEDIUM',
    alwaysAlert: false,
    retentionDays: 30,
    tags: ['api', 'header', 'security'],
  },
  [SECURITY_EVENT_TYPES.CSRF_VALIDATION_FAILED]: {
    label: 'CSRF Validation Failed',
    description: 'CSRF token validation failed',
    defaultRiskLevel: 'HIGH',
    alwaysAlert: true,
    retentionDays: 90,
    tags: ['api', 'csrf', 'security'],
  },
  [SECURITY_EVENT_TYPES.INVALID_INPUT_BLOCKED]: {
    label: 'Invalid Input Blocked',
    description: 'Potentially malicious input was blocked',
    defaultRiskLevel: 'HIGH',
    alwaysAlert: false,
    retentionDays: 90,
    tags: ['api', 'validation', 'security'],
  },

  // Data Security Events
  [SECURITY_EVENT_TYPES.SENSITIVE_DATA_ACCESSED]: {
    label: 'Sensitive Data Accessed',
    description: 'Sensitive data was accessed',
    defaultRiskLevel: 'LOW',
    alwaysAlert: false,
    retentionDays: 365,
    tags: ['data', 'sensitive', 'access'],
  },
  [SECURITY_EVENT_TYPES.SENSITIVE_DATA_EXPORTED]: {
    label: 'Sensitive Data Exported',
    description: 'Sensitive data was exported',
    defaultRiskLevel: 'HIGH',
    alwaysAlert: true,
    retentionDays: 365,
    tags: ['data', 'sensitive', 'export'],
  },
  [SECURITY_EVENT_TYPES.BULK_DATA_OPERATION]: {
    label: 'Bulk Data Operation',
    description: 'Bulk operation was performed on data',
    defaultRiskLevel: 'MEDIUM',
    alwaysAlert: false,
    retentionDays: 365,
    tags: ['data', 'bulk', 'operation'],
  },
  [SECURITY_EVENT_TYPES.PII_ACCESSED]: {
    label: 'PII Accessed',
    description: 'Personally identifiable information was accessed',
    defaultRiskLevel: 'MEDIUM',
    alwaysAlert: false,
    retentionDays: 365,
    tags: ['data', 'pii', 'compliance'],
  },

  // System Security Events
  [SECURITY_EVENT_TYPES.CONFIG_CHANGED]: {
    label: 'Configuration Changed',
    description: 'System configuration was changed',
    defaultRiskLevel: 'MEDIUM',
    alwaysAlert: false,
    retentionDays: 365,
    tags: ['system', 'config'],
  },
  [SECURITY_EVENT_TYPES.FEATURE_FLAG_CHANGED]: {
    label: 'Feature Flag Changed',
    description: 'Feature flag was toggled',
    defaultRiskLevel: 'LOW',
    alwaysAlert: false,
    retentionDays: 365,
    tags: ['system', 'feature-flag'],
  },
  [SECURITY_EVENT_TYPES.SECURITY_SCAN_COMPLETED]: {
    label: 'Security Scan Completed',
    description: 'Security scan finished',
    defaultRiskLevel: 'LOW',
    alwaysAlert: false,
    retentionDays: 90,
    tags: ['system', 'scan'],
  },
  [SECURITY_EVENT_TYPES.VULNERABILITY_DETECTED]: {
    label: 'Vulnerability Detected',
    description: 'Security vulnerability was detected',
    defaultRiskLevel: 'CRITICAL',
    alwaysAlert: true,
    retentionDays: 365,
    tags: ['system', 'vulnerability', 'security'],
  },
  [SECURITY_EVENT_TYPES.ANOMALY_DETECTED]: {
    label: 'Anomaly Detected',
    description: 'Unusual system behavior was detected',
    defaultRiskLevel: 'HIGH',
    alwaysAlert: true,
    retentionDays: 365,
    tags: ['system', 'anomaly', 'security'],
  },

  // Agent Security Events
  [SECURITY_EVENT_TYPES.AGENT_SENSITIVE_DATA_TO_LLM]: {
    label: 'Sensitive Data Sent to LLM',
    description: 'Agent tool with sensitive data executed and results sent to LLM provider',
    defaultRiskLevel: 'MEDIUM',
    alwaysAlert: true,
    retentionDays: 365,
    tags: ['agent', 'data-flow', 'sensitive'],
  },
  [SECURITY_EVENT_TYPES.AGENT_TOOL_BLOCKED_BY_POLICY]: {
    label: 'Agent Tool Blocked by Policy',
    description: 'Agent tool execution blocked because provider is not trusted at the required data sensitivity level',
    defaultRiskLevel: 'HIGH',
    alwaysAlert: true,
    retentionDays: 365,
    tags: ['agent', 'policy', 'blocked'],
  },

  // Integration Security Events
  [SECURITY_EVENT_TYPES.OAUTH_TOKEN_REFRESHED]: {
    label: 'OAuth Token Refreshed',
    description: 'OAuth access token was refreshed',
    defaultRiskLevel: 'LOW',
    alwaysAlert: false,
    retentionDays: 30,
    tags: ['integration', 'oauth'],
  },
  [SECURITY_EVENT_TYPES.OAUTH_TOKEN_REVOKED]: {
    label: 'OAuth Token Revoked',
    description: 'OAuth access token was revoked',
    defaultRiskLevel: 'MEDIUM',
    alwaysAlert: false,
    retentionDays: 365,
    tags: ['integration', 'oauth', 'revoked'],
  },
  [SECURITY_EVENT_TYPES.WEBHOOK_SIGNATURE_INVALID]: {
    label: 'Webhook Signature Invalid',
    description: 'Webhook request had invalid signature',
    defaultRiskLevel: 'HIGH',
    alwaysAlert: true,
    retentionDays: 90,
    tags: ['integration', 'webhook', 'security'],
  },
  [SECURITY_EVENT_TYPES.EXTERNAL_API_ERROR]: {
    label: 'External API Error',
    description: 'Error communicating with external API',
    defaultRiskLevel: 'MEDIUM',
    alwaysAlert: false,
    retentionDays: 30,
    tags: ['integration', 'api', 'error'],
  },
};
