// ===========================================
// TESTS: Module Registry
// ===========================================

import { describe, it, expect } from 'vitest';
import { getModule, getAllModules, getModuleNames } from './registry';

describe('module registry', () => {
  it('has 9 built-in modules', () => {
    expect(getAllModules()).toHaveLength(9);
  });

  it('getModule("email") returns valid definition', () => {
    const mod = getModule('email');
    expect(mod).toBeDefined();
    expect(mod!.name).toBe('email');
    expect(mod!.description).toBeTruthy();
  });

  it('getModule("tasks") returns valid definition', () => {
    const mod = getModule('tasks');
    expect(mod).toBeDefined();
    expect(mod!.name).toBe('tasks');
    expect(mod!.description).toBeTruthy();
  });

  it('getModule("entities") returns valid definition', () => {
    const mod = getModule('entities');
    expect(mod).toBeDefined();
    expect(mod!.name).toBe('entities');
    expect(mod!.description).toBeTruthy();
  });

  it('getModule("auth") returns valid definition', () => {
    const mod = getModule('auth');
    expect(mod).toBeDefined();
    expect(mod!.name).toBe('auth');
    expect(mod!.description).toBeTruthy();
  });

  it('getModule("nonexistent") returns undefined', () => {
    expect(getModule('nonexistent')).toBeUndefined();
  });

  it('getModuleNames() returns all 9 names', () => {
    const names = getModuleNames();
    expect(names).toContain('email');
    expect(names).toContain('tasks');
    expect(names).toContain('entities');
    expect(names).toContain('auth');
    expect(names).toContain('activities');
    expect(names).toContain('jobs');
    expect(names).toContain('settings');
    expect(names).toContain('security');
    expect(names).toContain('agent');
    expect(names).toHaveLength(9);
  });

  it('getModule("activities") returns valid definition', () => {
    const mod = getModule('activities');
    expect(mod).toBeDefined();
    expect(mod!.name).toBe('activities');
    expect(mod!.description).toBeTruthy();
  });

  it('getModule("security") returns valid definition', () => {
    const mod = getModule('security');
    expect(mod).toBeDefined();
    expect(mod!.name).toBe('security');
    expect(mod!.description).toBeTruthy();
    expect(mod!.schemaFile).toBeUndefined(); // Uses ActivityLog
    expect(mod!.seed).toBeUndefined(); // No seed
  });

  it('getModule("jobs") returns valid definition', () => {
    const mod = getModule('jobs');
    expect(mod).toBeDefined();
    expect(mod!.name).toBe('jobs');
    expect(mod!.description).toBeTruthy();
    expect(mod!.schemaFile).toBeUndefined(); // Uses Redis, not DB
    expect(mod!.seed).toBeUndefined(); // Types registered by app
  });

  it('getModule("agent") returns valid definition', () => {
    const mod = getModule('agent');
    expect(mod).toBeDefined();
    expect(mod!.name).toBe('agent');
    expect(mod!.description).toBeTruthy();
    expect(mod!.schemaFile).toBe('agent.prisma');
    expect(mod!.seed).toBeUndefined(); // Tools/roles registered by app
  });

  it('getModule("settings") returns valid definition', () => {
    const mod = getModule('settings');
    expect(mod).toBeDefined();
    expect(mod!.name).toBe('settings');
    expect(mod!.description).toBeTruthy();
    expect(mod!.seed).toBeTypeOf('function');
  });

  it('each module has required fields (name, description)', () => {
    for (const mod of getAllModules()) {
      expect(mod.name).toBeTruthy();
      expect(mod.description).toBeTruthy();
      // schemaFile is optional (security uses ActivityLog, jobs uses Redis)
      if (mod.name !== 'security' && mod.name !== 'jobs') {
        expect(mod.schemaFile).toBeTruthy();
      }
    }
  });

  it('modules with seed have a seed function defined', () => {
    for (const mod of getAllModules()) {
      if (mod.name === 'auth' || mod.name === 'activities' || mod.name === 'security' || mod.name === 'jobs' || mod.name === 'agent') {
        // Auth: models managed by auth framework
        // Activities: populated by application events
        // Security: events generated by application behavior
        // Jobs: types registered by consuming app at startup
        expect(mod.seed).toBeUndefined();
      } else {
        expect(mod.seed).toBeTypeOf('function');
      }
    }
  });
});
